### ISSUE TITLE
Animator Parameter's List Initialize as null in VR

### ISSUE THREAD

**Issue by kafeijao** [200Tigersbloxed/CVRParamLib#10]
Not sure if you're already on top of this. It seems `PlayerSetup.animatorManager.parameters` is null when starting the game in VR, it's fine when starting in Desktop. Branch: https://github.com/200Tigersbloxed/CVRParamLib/commit/bc53a1026140d2264544b873193fbc0c27924615

https://github.com/200Tigersbloxed/CVRParamLib/blob/bc53a1026140d2264544b873193fbc0c27924615/CVRParamLib/CVRParameterInstance.cs#L45-L51

Also, just out of curiosity, is there any reason why you're checking for avatar change in Update, when you already hooked into `PlayerSetup.SetupAvatar` ?

**Comment by 200Tigersbloxed** [comment]
This should be fixed in [c6d1a1a](https://github.com/200Tigersbloxed/CVRParamLib/commit/c6d1a1ae0bfd4234334378aa14aee42404f74488)
