### ISSUE TITLE
Support CVRParameterStreamEntry Parameters

### ISSUE THREAD

**Issue by 200Tigersbloxed** [200Tigersbloxed/CVRParamLib#3]
Add support for reading the `CVRParameterStream` component and it's `List<CVRParameterStreamEntry> entries` as an `AvatarParameter`. May take extra work because of the special enums (Type, TargetType, and ApplicationType)

**Comment by kafeijao** [comment]
By what I've seen in the decompiled code (note that I'm a noob at RE) on avatars it always uses `AvatarAnimator` as target type (if used on avatars) and all the parameters are set as floats.

By what I read in discord some of those parameters don't work, but I was too lazy to check due lack of a good way to do it, if you add this it will be so juicy for debugging. (I love this mod, thank you so much ^^)

**Comment by 200Tigersbloxed** [comment]
After some more research, this seems to be a duplicate of #4 , since the `CVRParameterStream` component seems to drive Parameters on the Animator Layer. Welcome to re-open if there's more information I'm missing out here.
