### ISSUE TITLE
Replace CVRAdvancedSettings with baseAnimator Parameters

### ISSUE THREAD

**Issue by bizzclaw** [200Tigersbloxed/CVRParamLib#4]
When using this with something like VRCFaceTracking, the paramaters for things like Eyex, EyesY, ect, aren't showing up in the JSON file.

This mod seems to only add things to the JSON if they're in the menu. This is a problem because I really don't want to fill my menu with all of my FaceTracking values.

It would be much better if all of the paramaters from the animator were added to the generated JSON.

Thank you.

**Comment by 200Tigersbloxed** [comment]
Would the parameters you're talking about be referenced to issue #3 ? (`CVRParameterStream`), or would this be something involving the `CVRFaceTracking` Component, or is this something specific only to the baseAnimator?

**Comment by bizzclaw** [comment]
I probably could of been more descriptive, but I'm pretty sure this is its own issue.
here's a JSON of my avatar's generated JSON file

```json
{
  "id": "avtr_f2813792-2cfb-455b-a470-7de5ecfae702",
  "name": "BizzMinase",
  "parameters": [
    {
      "name": "Eye Tracking",
      "input": {
        "address": "/avatar/parameters/Eye Tracking",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Eye Tracking",
        "type": "Bool"
      }
    },
    {
      "name": "WearNecklace",
      "input": {
        "address": "/avatar/parameters/WearNecklace",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/WearNecklace",
        "type": "Bool"
      }
    },
    {
      "name": "WearWatch",
      "input": {
        "address": "/avatar/parameters/WearWatch",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/WearWatch",
        "type": "Bool"
      }
    },
    {
      "name": "Wear Choker",
      "input": {
        "address": "/avatar/parameters/Wear Choker",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Wear Choker",
        "type": "Bool"
      }
    },
    {
      "name": "SelectOutfit",
      "input": {
        "address": "/avatar/parameters/SelectOutfit",
        "type": "Int"
      },
      "output": {
        "address": "/avatar/parameters/SelectOutfit",
        "type": "Int"
      }
    },
    {
      "name": "UndressOuter",
      "input": {
        "address": "/avatar/parameters/UndressOuter",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/UndressOuter",
        "type": "Bool"
      }
    },
    {
      "name": "UndressTop",
      "input": {
        "address": "/avatar/parameters/UndressTop",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/UndressTop",
        "type": "Bool"
      }
    },
    {
      "name": "Undress Bottom",
      "input": {
        "address": "/avatar/parameters/Undress Bottom",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Undress Bottom",
        "type": "Bool"
      }
    },
    {
      "name": "Undress Shoes",
      "input": {
        "address": "/avatar/parameters/Undress Shoes",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Undress Shoes",
        "type": "Bool"
      }
    },
    {
      "name": "Undress Inner",
      "input": {
        "address": "/avatar/parameters/Undress Inner",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Undress Inner",
        "type": "Bool"
      }
    },
    {
      "name": "Undress Gloves",
      "input": {
        "address": "/avatar/parameters/Undress Gloves",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/Undress Gloves",
        "type": "Bool"
      }
    },
    {
      "name": "HoodUp",
      "input": {
        "address": "/avatar/parameters/HoodUp",
        "type": "Float"
      },
      "output": {
        "address": "/avatar/parameters/HoodUp",
        "type": "Float"
      }
    },
    {
      "name": "HeartBeat Range",
      "input": {
        "address": "/avatar/parameters/HeartBeat Range",
        "type": "Float"
      },
      "output": {
        "address": "/avatar/parameters/HeartBeat Range",
        "type": "Float"
      }
    },
    {
      "name": "HeartBeat Volume",
      "input": {
        "address": "/avatar/parameters/HeartBeat Volume",
        "type": "Float"
      },
      "output": {
        "address": "/avatar/parameters/HeartBeat Volume",
        "type": "Float"
      }
    },
    {
      "name": "HeartRate Monitor",
      "input": {
        "address": "/avatar/parameters/HeartRate Monitor",
        "type": "Bool"
      },
      "output": {
        "address": "/avatar/parameters/HeartRate Monitor",
        "type": "Bool"
      }
    }
  ]
}
```
Here's a screenshot of my generated aas override controller's parameters
![Unity_gbBSDYushf](https://user-images.githubusercontent.com/3189582/184178738-dd49f732-6b44-4c5b-b34b-5a64bcc50adc.png)


Notice things like HRPercent (used by a very cool OSC application) are missing from the generated JSON.

As you can see, a lot of the parameters are not shown in the generated JSON file, and the only ones that do show up are ones that I've added to my Avatar's Advanced Parameters Menu, but the way CVR works is every parameter in the Controller, unless it starts with a "#" symbol, is automatically networkedl; It doesn't need to be in the menu to sync. For a lot of avatars I've been Working on, I don't tend to put any of the OSC controlled parameters into the menus.

Another thing I've just noticed - not to pile on here, but when parameters are added to a menu with a space in their name, that Space is removed from them in the Animator, so something like HeartRate Monitor becomes HeartRateMonitor, but in my JSON, it's becoming "HeartRate Monitor", the same as in the menu. That wouldn't be able to be controlled properly by OSC though, since the Paramater that's actually animated doesn't have that space.

**Comment by 200Tigersbloxed** [comment]
> but the way CVR works is every parameter in the Controller, unless it starts with a "#" symbol, is automatically networkedl;

This I did not know. I thought that only the ones in the Advanced Settings would sync. Thank you for the clarification. I will work on supporting reading parameters from the baseAnimator.

**Comment by bizzclaw** [comment]
Yeah I'm not surprised its not very well known and the documentation doesn't mention a lot of these things yet. A lot of people are also auto-converting avatars, which puts everything into the menu even though it doesn't need too.

**Comment by 200Tigersbloxed** [comment]
This change has been implemented in the [latest commit](https://github.com/200Tigersbloxed/CVRParamLib/commit/9bb9bed13f2f08e380d5e81b1cd69e8d06f4da7e) and is awaiting release.

**Comment by bizzclaw** [comment]
Whatever happened to this? I need to try building the latest version myself.

**Comment by 200Tigersbloxed** [comment]
Right as I was writing the release notes for the version that implemented this, @kafeijao made their own [OSC Mod](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/OSC), which is like a hundred times better than this lol. I'd highly recommend using that, however, if you wish, I can publish that draft release that's been sitting there for a good month now.
