### ISSUE TITLE
[Feature Request] Sending parameter changes out

### ISSUE THREAD

**Issue by kafeijao** [200Tigersbloxed/CVRParamLib#5]
So far there is the `/avatar/change` endpoint. I wanted a similar one for parameter changes, so I could react externally to parameter changes from my avatar (maybe with a toggle on the config for performance reasons).

**Comment by 200Tigersbloxed** [comment]
So something like a `/parameter/change` endpoint for when a parameter is changed?

EDIT: And send the data like
```cs
object[] data = {"parameterName", parameterValue}
```

**Comment by kafeijao** [comment]
I didn't realize vrc supported output parameters when they change. Apparently they use the same address for input and output, so I guess to make it compatible with existing OSC apps doing the same would probably be the best idea.
So `/avatar/parameters/name` and I haven't tested since I didn't know about this before, but I assume.

As for the data format I would need to check how vrc currently does it. But I also feel like doing the same output would be great. I guess its time for me to fire up VRC `;_;`  it's for a good cause. I just did it `;_;`

Ok so, it seems when I load a new avatar it will iterate throught my parameters, sending them to `/avatar/parameters/name` with a single arg containing the parameter value. And from then forward only send if they change.

And the data format is just simply the value in it's corresponding type, so something like:

Floats: `object[] data = 1.0;`
Bools: `object[] data = false;`
Ints: `object[] data = 25;`
Triggers: They are ignored

Thanks for looking into this! If there are any more questions or something I can help with do tell!

**Comment by 200Tigersbloxed** [comment]
This change has been implemented in the [latest commit](https://github.com/200Tigersbloxed/CVRParamLib/commit/9bb9bed13f2f08e380d5e81b1cd69e8d06f4da7e) and is awaiting release.
