### ISSUE TITLE
Check if Cached Parameters Changed Values before Updating

### ISSUE THREAD

**Issue by kafeijao** [200Tigersbloxed/CVRParamLib#9]
I was able to see this when I hooked to the `changeAnimatorParam` method. Once I changed a parameter via OSC, lets say `outfit` to 1, `changeAnimatorParam` started to get spammed setting `outfit` to 1 (multiple times a second), even after I changed to an avatar that doesn't have that parameter it kept spamming it.

I experience this on: https://github.com/200Tigersbloxed/CVRParamLib/commit/30ddc1aebdcb5ded86cb5ec3f7d4e5eb3b687d2a

**Comment by 200Tigersbloxed** [comment]
This is normal behavior, since all cached parameters are updated on Update void. I was working on a way to detect when the parameters did change, but it's still a little bit jank. Nonetheless, will be done eventually, probably before next release.

**Comment by kafeijao** [comment]
Neat, great work btw! I love the debug menu, you have no idea how much time you saved me debugging stuff
If there is something you need help with do tell, I kind of got addicted >.>

**Comment by 200Tigersbloxed** [comment]
Implemented in [c6d1a1a](https://github.com/200Tigersbloxed/CVRParamLib/commit/c6d1a1ae0bfd4234334378aa14aee42404f74488)

**Comment by kafeijao** [comment]
Okay so the issue where it would spam the parameter update is gone. But if I change the parameter in-game the mod will detect the change and change back to what the last OSC msg changed.

Outfit = 0
1. I change the outfit to 1 via OSC
2. The mod changed my outfit to 1
3. I change my outfit to 2 with the in-game AAS menu
4. The game changes my outfit to 2
5. The mod instantly changes my outfit back to 1

The 5th step shouldn't happen.

**Comment by 200Tigersbloxed** [comment]
> But if I change the parameter in-game the mod will detect the change and change back to what the last OSC msg changed.

This issue has been moved to #11
